---
title: ""
---

<!--Want to put something here such as an image or plot that captures some of the things I work on or produce to g=ive an idea of the research I do-->

<!--Introduction paragraph-->

<br>

<style>

h1, h3 {
  
  font-weight: bold;
  text-align: center;
  
}

.blog-section {

  text-align: right;
  float: right;
  width: 45%;
  
}

.notebook-section {

  text-align: left;
  float: left;
  width: 45%;
  
}

.blogpost {

  background-color: #D3D3D3;
  position: relative;
  text-align: right;
  float: right;
  height: 100px;
  width: 100%;
  border-style: outset;
    
}

.notebook {

  background-color: #D3D3D3;
  position: relative;
  text-align: left;
  float: left;
  height: 100px;
  width: 100%;
  border-style: outset;
    
}

.textcontainer {

  float: right;
  display: block;
  background-color: #D3D3D3;
  font-size: 11px;
  font-weight: bold;
  position: relative;
  word-wrap: break-word;
  top: 5%;
  bottom: 5%;
  width: 100%;
  height: 100%;
  overflow: auto;
  
}

.title {
  
  top: 15%;
  font-size: 115%;
  text-align: center;
  
}

.description {

  top: 25%;
  color: #666666;
  font-size: 115%;
  text-align: left;
  
}

</style>


<h1>Posts</h1>

<br>
<br>

<div class="notebook-section">

<h3>Notebooks</h3>

<br>
<br>

<div class="notebook">

<div class="textcontainer">
    
  <p class="title">
  August 29, 2017:  Bayes Classifier Associating Columbia authors to Research topics
  </p>
        
  <p class="description">
  Finding Columbia University author's research area using Bayes Classification. A fun weekend project...
  </p>

</div>

</div>

</div>

<div class="blog-section">

<h3>Blog</h3>

<br>
<br>

<div class="blogpost">

<div class="textcontainer">
    
  <p class="title">
  September 13th, 2017:   Hello World!
  </p>
        
  <p class="description">
  Hello everybody! Thanks for visiting my very under construction site. I'll be adding more notebooks and blog posts in the future. Hopefully they'll be useful and readable. Stay tuned!
  </p>

</div>

</div>

</div>
